project:
  type: website
  resources: assets

website:
  title: "Your Name"
  navbar:
    background: "#5a0722"
    foreground: "#ffffff"
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/
      - icon: github
        href: https://github.com/
      - icon: file-pdf
        href: assets/resume.pdf
format:
  html:
    theme:
      light: flatly
      dark: darkly
        # - custom.scss
    toc: true

execute:
  freeze: auto

